# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-02-11 01:12
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Book',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('isbn', models.SlugField(max_length=20, unique=True)),
                ('book_type', models.CharField(blank=True, choices=[('0', 'Neuf'), ('1', 'Occassion')], max_length=2, null=True)),
                ('vendor', models.CharField(blank=True, max_length=200, null=True)),
                ('country', models.CharField(blank=True, max_length=200, null=True)),
                ('description', models.TextField(blank=True, null=True)),
                ('price', models.CharField(blank=True, max_length=10, null=True)),
                ('shop_img', models.URLField(blank=True, null=True)),
                ('shop_link', models.URLField(blank=True, null=True)),
            ],
        ),
    ]
