# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-02-26 18:54
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crawler', '0005_auto_20170222_2111'),
    ]

    operations = [
        migrations.AddField(
            model_name='book',
            name='not_found',
            field=models.BooleanField(default=False),
        ),
    ]
